name: Create release artifacts

on:
  push:
    tags:
      - 'speedb/v*'

permissions:
  contents: write # Needed for release assets upload
  id-token: write # Needed for AWS credentials setting

jobs:
  build:
    runs-on: [self-hosted, ubuntu, asrunner]

    container:
      image: centos:7.9.2009

    steps:
      - name: pre
        run: |
          yum install -y centos-release-scl epel-release
          yum install -y make devtoolset-11-gcc-c++ \
            coreutils wget unzip which git python3 openssl-devel \
            libzstd-devel lz4-devel snappy-devel zlib-devel \
            java-1.8.0-openjdk-devel
          echo "PATH=/opt/rh/devtoolset-11/root/usr/bin:${PATH}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${GITHUB_REF_NAME#speedb/v}" >> $GITHUB_ENV

      - name: Install CMake
        run: |
          CMAKE_RELEASE=3.20.1
          wget https://github.com/Kitware/CMake/releases/download/v${CMAKE_RELEASE}/cmake-${CMAKE_RELEASE}.tar.gz
          tar xf cmake-${CMAKE_RELEASE}.tar.gz
          cd cmake-${CMAKE_RELEASE}
          ./bootstrap
          make -j$(nproc) && make install
          cd .. && rm -rf cmake-${CMAKE_RELEASE}*

      - name: Install awscli
        run: |
          wget "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -O "awscliv2.zip"
          unzip awscliv2.zip
          ./aws/install
          rm -rf aws awscliv2.zip

      - uses: actions/checkout@v3

      - run: mkdir "$GITHUB_WORKSPACE/out"

      - name: Build and package release libraries
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DPORTABLE=1 -DWITH_GFLAGS=0 -DWITH_SNAPPY=1 -DWITH_LZ4=1 -DWITH_ZLIB=1 -DWITH_ZSTD=1
          mkdir -p "$GITHUB_WORKSPACE/out/root"
          DESTDIR="$GITHUB_WORKSPACE/out/root" make -j$(nproc) install
          ( cd "$GITHUB_WORKSPACE/out/root" && tar czf ../speedb-${RELEASE_VERSION}.tar.gz . )
          rm -rf "$GITHUB_WORKSPACE/out/root"
          rm -rf build

      - name: Build release Jar
        run: |
          make clean
          LIB_MODE=static DEBUG_LEVEL=0 PORTABLE=1 JAVA_HOME=/usr/lib/jvm/java-openjdk make -j$(nproc) rocksdbjavastatic
          cp "java/target/speedbjni-${RELEASE_VERSION}-linux64.jar" "$GITHUB_WORKSPACE/out"

      - name: Generate checksums
        run: |
          for f in $GITHUB_WORKSPACE/out/*; do
            sha256sum "$f" > "$f.sha256"
          done

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: false
          files: |
            ${{ env.GITHUB_WORKSPACE }}/out/speedb-${{ env.RELEASE_VERSION }}.tar.gz
            ${{ env.GITHUB_WORKSPACE }}/out/speedb-${{ env.RELEASE_VERSION }}.tar.gz.sha256
            ${{ env.GITHUB_WORKSPACE }}/out/speedbjni-${{ env.RELEASE_VERSION }}-linux64.jar
            ${{ env.GITHUB_WORKSPACE }}/out/speedbjni-${{ env.RELEASE_VERSION }}-linux64.jar.sha256

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Upload artifacts to S3
        run: |
          aws s3 cp "$GITHUB_WORKSPACE/out" "s3://spdb-github-artifacts/release-${RELEASE_VERSION}" --recursive
          rm -rf "$GITHUB_WORKSPACE/out"
