# This workflow will build Speedb on a Mac OS server
#
# This workflow assumes the self hosted runner on a Mac machine is ready.
# The Mac OS server must have all the tools and software required for Speedb building to be installed


name: Build on Mac 

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: macOSi86 # a test self hosted runner on a vm with MacOS
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: 'build'
      run: |
        export JAVA_HOME=/usr/local/opt/openjdk@11
        export CPPFLAGS="-I/usr/local/opt/openjdk@11/include"
        export CXXFLAGS="-I/usr/local/opt/openjdk@11/include"
        DEBUG_LEVEL=0 make -j 4 rocksdbjavastatic
