name: Build on Mac

on: 
  workflow_call:
    inputs:
      verSion:
        required: true
        type: string
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-11

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options.
        java-version: '8'
    - name: build jar
      run: |
        echo $JAVA_HOME
        export CPPFLAGS="-I$JAVA_HOME/include"
        export CXXFLAGS="-I$JAVA_HOME/include"
        brew install zlib
        brew install bzip2 lz4 snappy
        ROCKSDB_DISABLE_JEMALLOC=1 PORTABLE=1 DEBUG_LEVEL=0 make -j $(nproc) rocksdbjavastatic

    - name: 'upload artifacts'    #This step executed only when this workflow is called by another and a version is provided
      if: inputs.verSion != ' '
      run: aws s3 cp java/target/libspeedbjni-osx-x86_64.jnilib s3://spdb-builder/jar_test/v${{ inputs.verSion }}/libspeedbjni-osx-x86_64.jnilib
